apiVersion: v1
kind: Secret
metadata:
  name: system-vibe-secrets
  namespace: system-vibe
type: Opaque
stringData:
  DB_USER: "systemvibe"
  DB_PASSWORD: "devpassword"
  DB_NAME: "systemvibe"
  API_PORT: "3000"
  # Thêm các biến môi trường khác nếu cần
  JWT_SECRET: "czPylvCEb5n1j3EwnFTUQz1sHlucQHXevlk6F50PXPU="
